Spandana N R AMB2261

In [ ]:
import pandas as pd
production=pd.Series([30,60,45,25],
                     index=["wheat","rice","maize","barley"])
print(production)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
#by crop name[label]
print(production["rice"])
print(production.loc["rice"])

60
60

In [ ]:
#by positioning
print(production.iloc[0])
print(production.iloc[2])

30
45

In [ ]:
print(production.mean())
print(production.sum())
print(production.max())
print(production.idxmax())

40.0
160
60
rice

In [ ]:
#increase all crop production by 10%
incresed_production=production*1.10
print(incresed_production)

wheat     33.0
rice      66.0
maize     49.5
barley    27.5
dtype: float64

In [ ]:
#crops with production greater than 40 tons
high_production=production[production>40]
print(high_production)
print()

print(production>40)

rice     60
maize    45
dtype: int64

wheat     False
rice       True
maize      True
barley    False
dtype: bool

In [ ]:
import pandas as pd
df=pd.DataFrame({"name":["sonu","suma","sindhu"],
                 "age":[20,21,19],
                 "city":["uk","usa","london"]}
                 ,index=["a","b","c"])
print(df)
print()
print(df.loc["b"])

     name  age    city
a    sonu   20      uk
b    suma   21     usa
c  sindhu   19  london

name    suma
age       21
city     usa
Name: b, dtype: object

In [ ]:
print(df.loc[["a","b"],["name","city"]])

   name city
a  sonu   uk
b  suma  usa

In [ ]:
print(df.loc["a":"c"])

     name  age    city
a    sonu   20      uk
b    suma   21     usa
c  sindhu   19  london

In [ ]:
import pandas as pd
df=pd.DataFrame({"name":["sonu","suma","sindhu"],
                 "age":[20,21,19],
                 "city":["uk","usa","london"]}
                 ,index=["a","b","c"])
print(df)
print(df.loc[df["age"]>28,["name","age"]])

     name  age    city
a    sonu   20      uk
b    suma   21     usa
c  sindhu   19  london
Empty DataFrame
Columns: [name, age]
Index: []

In [ ]:
print(df.iloc[[0,2]])

     name  age    city
a    sonu   20      uk
c  sindhu   19  london

In [ ]:
print(df.iloc[[0,2],[1,2]])

   age    city
a   20      uk
c   19  london

In [ ]:
import pandas as pd
data={"farm":["farm A","farm B","farm C","farm D"],
   "crop":["wheat","rice","maize","barley"],
      "area_hectares":[10,15,8,12],
      "production_tons":[30,60,24,36]}
df=pd.DataFrame(data)
print(df)

     farm    crop  area_hectares  production_tons
0  farm A   wheat             10               30
1  farm B    rice             15               60
2  farm C   maize              8               24
3  farm D  barley             12               36

In [ ]:
df.head(2) #first few rows

     farm   crop  area_hectares  production_tons
0  farm A  wheat             10               30
1  farm B   rice             15               60

In [ ]:
df.tail(2) # last bottom rows

     farm    crop  area_hectares  production_tons
2  farm C   maize              8               24
3  farm D  barley             12               36

In [ ]:
df.info() #get basic info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   farm             4 non-null      object
 1   crop             4 non-null      object
 2   area_hectares    4 non-null      int64
 3   production_tons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe() #summary statistics

       area_hectares  production_tons
count       4.000000         4.000000
mean       11.250000        37.500000
std         2.986079        15.779734
min         8.000000        24.000000
25%         9.500000        28.500000
50%        11.000000        33.000000
75%        12.750000        42.000000
max        15.000000        60.000000

In [ ]:
# add a new coloum(yield)
#yeild= production/yield
df["yield_per_ton_hactare"]=df["production_tons"]/df["area_hectares"]
print(df)

     farm    crop  area_hectares  production_tons  yield_per_ton_hactare
0  farm A   wheat             10               30                    3.0
1  farm B    rice             15               60                    4.0
2  farm C   maize              8               24                    3.0
3  farm D  barley             12               36                    3.0

In [ ]:
print(df.iloc[[1,3]])

     farm    crop  area_hectares  production_tons  yield_per_ton_hactare
1  farm B    rice             15               60                    4.0
3  farm D  barley             12               36                    3.0

In [ ]:
df.iloc[[1,3]]

     farm    crop  area_hectares  production_tons  yield_per_ton_hactare
1  farm B    rice             15               60                    4.0
3  farm D  barley             12               36                    3.0

In [ ]:
df.iloc[[0,3,2],[1,2,3]]

     crop  area_hectares  production_tons
0   wheat             10               30
3  barley             12               36
2   maize              8               24

In [ ]:
print(df.loc[[1,2],["farm","crop"]])

     farm   crop
1  farm B   rice
2  farm C  maize

In [ ]:
print(df.loc[0:3])

     farm    crop  area_hectares  production_tons  yield_per_ton_hactare
0  farm A   wheat             10               30                    3.0
1  farm B    rice             15               60                    4.0
2  farm C   maize              8               24                    3.0
3  farm D  barley             12               36                    3.0

In [ ]:
#filter farms growing wheat
print(df["crop"]=="wheat")
print()
wheat_farms=df[df["crop"]=="wheat"]
print(wheat_farms)

0     True
1    False
2    False
3    False
Name: crop, dtype: bool

     farm   crop  area_hectares  production_tons  yield_per_ton_hactare
0  farm A  wheat             10               30                    3.0

In [ ]:
#farms with yield greater than 3
high_yield=df[df["yield_per_ton_hactare"]>3]
print(high_yield)

     farm  crop  area_hectares  production_tons  yield_per_ton_hactare
1  farm B  rice             15               60                    4.0

In [ ]:
#sort farms by highest production
sorted_df=df.sort_values(by="production_tons",ascending=False)
print(sorted_df)

     farm    crop  area_hectares  production_tons  yield_per_ton_hactare
1  farm B    rice             15               60                    4.0
3  farm D  barley             12               36                    3.0
0  farm A   wheat             10               30                    3.0
2  farm C   maize              8               24                    3.0

In [ ]:
avg_yield=df.groupby("crop")["yield_per_ton_hactare"].sum()
print(avg_yield)

crop
barley    3.0
maize     3.0
rice      4.0
wheat     3.0
Name: yield_per_ton_hactare, dtype: float64